# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# prompt
if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}[\[\033[01;33m\]\u\[\033[00m\]@\[\033[01;34m\]\h\[\033[00m\]:\[\033[01;33m\]\w\[\033[00m\]]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
 fi

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Alias definitions.
if [ -f ~/.config/bash/bash_aliases ]; then
    . ~/.config/bash/bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# exports
export EDITOR=nvim
export LANG=en_US.UTF-8
export HISTCONTROL=ingnoreboth

# vi mode
set -o vi

## make delete key work in st terminal
tput smkx

## Archive extraction
ex ()
{
if [ -f $1 ]; then
	case $1 in
	*.tar.bz2)	tar xjf $1	;;
	*.tar.gz)	tar xzf $1	;;
	*.bz2)		bunzip2 $1	;;
	*.gz)		gunzip $1	;;
	*.rar)		unrar x $1	;;
	*.tar)		tar xf $1	;;
	*.tbz2)		tar xjf $1	;;
	*.tgz)		tar xzf $1	;;
	*.zip)		unzip $1	;;
	*.Z)		uncompress $1	;;
	*.7z)		7z x $1		;;
	*.deb)		ar x $1		;;
	*.tar.xz)	tar xf $1	;;
	*.tar.zst)	unzstd $1	;;
	*)		echo "'$1' cannot be extracted via ex()" ;;

    esac
else
    echo "'$1'is not a valid file"
fi
}

dfetch
