#!/bin/bash

#Number of snapshots allowed
sn=5

red='\033[0;31m'
nc='\033[0m'
yellow='\033[1;33m'

#Root subvolume device
rsvdv="$(df -Th | grep btrfs | grep /$ | cut -d' ' -f 1)"

#Current date
cdt=`date | sed 's/ /-/g'`

#Root subvolume
rsv="$(sudo btrfs subvolume list / | grep "level 5" | head -n1 | awk '{print $9}')"

#Snapshot subvolume
ssv="$(sudo btrfs subvolume list / | grep "level 5" | grep snapshot | awk '{print $9}')"

#Number of root snapshots
rsl="$(sudo btrfs subvolume list / | grep snapshots | grep root | wc -l)"

#Oldest root snapshot
ors="$(sudo btrfs subvolume list / | grep snapshots | grep root | awk '{print $NF}' | head -n1)"

#mount Root subvolume device to /mnt
sudo mount $rsvdv /mnt

#MUST be in this directory to perform task
cd /mnt

#Create snapshot and place in snapshot directory
sudo btrfs subvolume snapshot $rsv $ssv/root-$cdt

#remove a snapshot if there are more than 5
if [ "$rsl" -ge "$sn"  ]; then
	printf "${red} removing oldest snapshot... ${nc}\n"
	sudo btrfs subvolume delete $ors
else
	printf "${yellow} too few snapshots... ${nc}\n"
	printf "${yellow} not deleting anything ${nc}\n"
fi



cd $HOME
sudo umount /mnt
exit
