#!/bin/bash
set -e
#number of snapshots allowed
sn=5

red='\033[0;31m'
nc='\033[0m'
yellow='\033[1;33m'

#home subvolume device
hsvdv="$(df -Th | grep btrfs | grep home | cut -d' ' -f 1)"

#current date
cdt=`date | sed 's/ /-/g'`

#home subvolume
hsv="$(sudo btrfs subvolume list / | grep "level 5" | grep home | awk '{print $NF}')"

#snapshot subvolume
ssv="$(sudo btrfs subvolume list / | grep "level 5" | grep snapshot | awk '{print $NF}')"

#number of home snapshots
hsl="$(sudo btrfs subvolume list / | grep snapshots/ | grep home | wc -l)"

#oldest home snapshot
ohs="$(sudo btrfs subvolume list / | grep snapshots | grep home | awk '{print $NF}' | head -n1)"

#Mount home subvolume to /mnt
if [ -e "$hsvdv" ]; then
    sudo mount $hsvdv /mnt
    printf "${yellow} mounted $hsvdv to /mnt${nc}\n"
else
    printf "${red} no btrfs drives found${nc}\n" && exit 1
fi

#MUST be in /mnt to perform task
cd /mnt

# Check home subvolume exists...
if [ -e "$hsv" ]; then
    printf "${yellow} found home subvolume...${nc}\n"
else
    printf "${red} no home subvolume found... exiting${nc}\n" && exit 1
fi

# check snapshot subvolume exists...
if [ -e "$ssv" ]; then
    printf "${yellow} found snapshot suvolume...${nc}\n"
else
    printf "${red} no snapshot subvolume found${nc}\n" && exit 1
fi

#Make snapshot and place in snapshot directory
sudo btrfs subvolume snapshot $hsv $ssv/home-$cdt

#remove a home snapshot if there are more than 5
if [ "$hsl" -ge "$sn" ]; then
    printf "${red} removing oldest snapshot... ${nc}\n"
    sudo btrfs subvolume delete $ohs
else
    printf "${yellow} too few snapshots...\n"
    printf "not deleting anything ${nc}\n"
fi

cd $HOME

sudo umount /mnt
exit
